# Generated by Django 4.2.30 on 2026-09-09 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Моё племя', max_length=100)),
                ('food', models.IntegerField(default=50)),
                ('wood', models.IntegerField(default=30)),
                ('stone', models.IntegerField(default=20)),
                ('population', models.IntegerField(default=5)),
                ('max_population', models.IntegerField(default=5)),
                ('hut_level', models.IntegerField(default=0)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamesession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tribesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Охотник', max_length=100)),
                ('task', models.CharField(choices=[('idle', 'Свободен'), ('hunting_5', 'Охота (5 мин)'), ('hunting_10', 'Охота (10 мин)'), ('hunting_40', 'Охота (40 мин)'), ('wood_2', 'Сбор дерева (2 мин)'), ('wood_10', 'Сбор дерева (10 мин)'), ('stone_2', 'Сбор камней (2 мин)'), ('stone_10', 'Сбор камней (10 мин)'), ('building', 'Строительство хижины'), ('dead', 'Мёртв')], default='idle', max_length=20)),
                ('task_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('task_start_time', models.DateTimeField(blank=True, null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribesmen', to='game.tribe')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tribe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='game.tribe')),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
    ]
